# Generated by Django 5.1 on 2025-04-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nolimitholdemhand',
            name='force_reveal_cards_for_player_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
