# Generated by Django 5.1 on 2025-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='background_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
