# Generated by Django 5.1 on 2024-11-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0002_alter_tableinvite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinvite',
            name='code',
            field=models.CharField(editable=False, max_length=22, unique=True),
        ),
    ]
