# Generated by Django 5.1 on 2024-09-13 19:06

import django.db.models.deletion
import shortuuid.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0002_tablepermissions_can_deal_alter_tableinvite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinvite',
            name='code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.CreateModel(
            name='NoLimitHoldEmChipAdjusment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chip_adjustments', to='pokerapp.tablemember')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_adjustments', to='pokerapp.nolimitholdemgameplayer')),
            ],
        ),
    ]
