# Generated by Django 5.1 on 2024-10-24 12:50

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0003_rename_i_won_or_lost_hand_tablenotificationsettings_i_lost_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nolimitholdemhand',
            name='players_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='pokerapp.nolimitholdemgameplayer'),
        ),
        migrations.AlterField(
            model_name='tableinvite',
            name='code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
