# Generated by Django 5.1 on 2024-10-24 14:20

import django.db.models.deletion
import django.utils.timezone
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0004_nolimitholdemhand_players_turn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nolimitholdemhand',
            name='players_turn',
        ),
        migrations.AddField(
            model_name='currentgame',
            name='last_move',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentgame',
            name='members_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='pokerapp.tablemember'),
        ),
        migrations.AlterField(
            model_name='tableinvite',
            name='code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
