# Generated by Django 5.1 on 2024-12-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0004_nolimitholdemchipadjustment_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableinvite',
            options={'ordering': ['-created']},
        ),
    ]
