# Generated by Django 5.1 on 2024-12-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0006_nolimitholdemhand_hand_number_table_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='join_on_account_sign_up',
            field=models.BooleanField(default=False),
        ),
    ]
