# Generated by Django 5.1 on 2024-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0007_table_join_on_account_sign_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgame',
            name='last_move',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currentgame',
            name='selected_game',
            field=models.CharField(choices=[('NO_LIMIT_HOLD_EM', 'No Limit Hold Em')], max_length=40),
        ),
    ]
