# Generated by Django 5.1 on 2024-12-31 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0008_alter_currentgame_last_move_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nolimitholdemhand',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='currentgame',
            name='selected_game',
            field=models.CharField(choices=[('NO_LIMIT_HOLD_EM', 'No Limit Hold Em'), ('STAGE_10', 'Stage 10')], max_length=40),
        ),
        migrations.CreateModel(
            name='Stage10Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game_json', models.JSONField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_10_games', to='pokerapp.table')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AddField(
            model_name='currentgame',
            name='stage_10_game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokerapp.stage10game'),
        ),
        migrations.CreateModel(
            name='Stage10GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_sitting', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pokerapp.stage10game')),
                ('table_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_10_players', to='pokerapp.tablemember')),
            ],
        ),
    ]
