# Generated by Django 5.1 on 2024-12-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0009_alter_nolimitholdemhand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage10game',
            name='game_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
