# Generated by Django 5.1 on 2025-01-04 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0010_alter_stage10game_game_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage10game',
            name='game_json',
        ),
        migrations.AddField(
            model_name='stage10gameplayer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stage10gameplayer',
            name='stage',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
