# Generated by Django 5.1 on 2025-01-08 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0012_alter_nolimitholdemhand_hand_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgame',
            name='no_limit_hold_em_game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_game', to='pokerapp.nolimitholdemgame'),
        ),
    ]
