# Generated by Django 5.1 on 2025-01-25 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0013_alter_currentgame_no_limit_hold_em_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage10Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(null=True)),
                ('round_json', models.JSONField()),
                ('round_number', models.BigIntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='pokerapp.stage10game')),
                ('players', models.ManyToManyField(to='pokerapp.stage10gameplayer')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
