# Generated by Django 5.1 on 2025-02-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0014_stage10round'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage10game',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
