# Generated by Django 5.1 on 2025-03-07 01:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapp', '0015_stage10game_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTablePermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('permissions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokerapp.tablepermissions')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_permissions', to='pokerapp.table')),
            ],
        ),
    ]
